---
name: montag-build-push-arm32v7-ghcr

on:
  push:
    branches:
      - 'main'
  pull_request:
  workflow_dispatch:
  repository_dispatch:
  schedule:
    - cron: '0 12 15 * *'

jobs:
  build-image:
    name: Call Docker Build
    uses: mmguero-dev/docker-build-workflow/.github/workflows/reusable-docker-build.yaml@main
    permissions:
      contents: read
      actions: write
      packages: write
      pull-requests: write
    with:
      context: .
      file: ./docker/Dockerfile.arm32v7
      cancel-previous-runs: true
      dockerhub-enable: false
      ghcr-enable: true
      image-names: |
        ghcr.io/${{ github.repository_owner }}/montag
      tag-rules: |
        type=raw,value=arm32v7,enable={{is_default_branch}}
        type=raw,value=stable-arm32v7-{{date 'YYYYMMDDHHmmss'}},enable={{is_default_branch}}
      platforms: linux/arm/v7
